chat_system/urls.py
from django.urls import path
from django.urls import reverse_lazy
from .views import *

urlpatterns = [
    path('chatlist/', chat_list, name='chat_list'),
    path('create-chat/<int:pk>/', createchat, name='create-chat'),
    path('chat/<int:pk>/', chat_detail, name='chat-detail'),
    path('chat/', chat_base, name='chat'),
    path('chat/<int:pk>/send-message/', SendMessageView.as_view(), name='send-message'),
]

app_name = 'chat_system'

core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('cocon.urls')),
    path('', include('post_system.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('chat_system.urls')),
    path('', include('notification_system.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

urlpatterns = [
    path('login/', LoginView.as_view(template_name='user/login.html' , extra_context={'next': reverse_lazy('cocon:home')}), name='login'),
    path('register/', RegisterView.as_view(template_name='user/register.html'), name='register'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('user:login')), name='logout'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('update-user-info/<int:pk>/', UpdateUserInfo.as_view(), name='update-user-info'),
    path('follow/<int:pk>/', FollowUser.as_view(), name='follow'),
]

app_name = 'user'

chat_system/models.py
from django.db import models
from user.models import CustomUser


class Chat(models.Model):
    members = models.ManyToManyField(CustomUser, related_name='chats')


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='messages')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

    def __str__(self):
        return self.content
    
    class Meta:
        ordering = ('created_at',)

chat_system/views.py
from django.shortcuts import render
from .models import *
from django.shortcuts import get_object_or_404
from django.views import View
from django.shortcuts import redirect
from django.http import HttpResponse

def createchat(request, pk):
    user1 = get_object_or_404(CustomUser, pk=request.user.pk)
    user2 = get_object_or_404(CustomUser, pk=pk)
    chat = Chat.objects.filter(members__id=user1.id).filter(members__id=user2.id)
    if chat.exists():
        return redirect('chat_system:chat-detail', pk=chat[0].pk)
    else:
        chat = Chat.objects.create()
        chat.members.add(user1, user2)
        return redirect('chat_system:chat-detail', pk=chat.pk)

def chat_detail(request, pk):
    chat = get_object_or_404(Chat, pk=pk)
    receiver = chat.members.all().exclude(id=request.user.id)[0]
    messages = chat.messages.all()
    for message in messages:
        if message.sender != request.user:
            message.is_seen = True
            message.save()
    return render(request, 'chat_system/chat.html', {'chat': chat, 'messages': messages, 'receiver':receiver})

def chat_list(request):
    if request.method == 'GET':
        chats = Chat.objects.filter(members__id=request.user.id)
        return render(request, 'chat_system/chat_list.html', {'chats': chats})

def chat_base(request):
    if request.method == 'GET':
        return render(request, 'chat_system/chat_base.html')


class SendMessageView(View):
    def post(self, request, *args, **kwargs):
        chat_id = kwargs.get('pk')
        chat = Chat.objects.filter(pk=chat_id)
        content = request.POST.get('content')
        sender = request.user
        message = Message.objects.create(chat=chat[0],
                            sender=sender,
                            content=content)
        message.save()
        return redirect('chat_system:chat-detail', pk=chat_id)

templates/chat_system/chat.html
{% extends 'chat_system/chat_base.html' %}

{% block chat %}
{% load static %}

<div class="chat-container">
    <a href="{% url 'user:profile' receiver.id %}">
    <div class="chat-header">
        <img src="{{receiver.avatar.url}}" alt="Profile Picture">
        <h2>{{receiver.username}}</h2>
        <span>Status: Online</span>
    </div>
    </a>
    <div class="chat-messages" id="chat-messages">
        {% if messages %}
            {% for message in messages %}
                {% if message.sender == request.user %}
                    <div class="message sent-by-user">
                        <p><strong>You:</strong> {{message}}</p>
                        <span class="timestamp">{{message.created_at}}</span>
                    </div>
                {% else %}
                    <div class="message received">
                        <p><strong>{{receiver.username}}:</strong> {{message}}</p>
                        <span class="timestamp">{{message.created_at}}</span>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <h1 class="empty-sign">Тут поки пусто</h1>
        {% endif %}
    </div>
    <form action="{% url 'chat_system:send-message' chat.id%}" method="post" id="messageForm">
    {% csrf_token %}
    <div class="chat-input">
        <textarea placeholder="Type your message..." name="content" required></textarea>
        <button type="submit"><i class="fas fa-paper-plane"></i></button>
    </div>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var chatMessages = document.getElementById('chat-messages');
        chatMessages.scrollTop = chatMessages.scrollHeight; // Scroll to bottom on load
    });
</script>
{% endblock %}

templates/chat_system/chat_base.html
{% extends 'cocon/home.html' %}

{% block content %}
{% load static %}

{% load custom_tags %}
<link rel="stylesheet" href="{% static '/css/chat.css' %}">

{% block chat %}
{% endblock %}

{% include 'chat_system/chat_list.html' %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    $.ajax({
        url: "{% url 'chat_system:chat_list' %}",
        success: function(data) {
            $("#users-menu").html(data);  
        },
        error: function(xhr, status, error) {
            console.error("Error fetching chat list:", status, error);
        }
    });
});
</script>
{% endblock %}

templates/chat_system/chat_list.html
{% load custom_tags %}

<div class="users-menu" id="users-menu">
    <h2>Повідомлення</h2>
    <ul>
        {% if chats %}
            {% for chat in chats %}
            {{chat|remove_request_user:request.user.id}}
            {% endfor %}
        {% else %}
        <h1>Пусто</h1>
        {% endif %}
    </ul>
</div>