core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('cocon.urls')),
    path('', include('post_system.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('chat_system.urls')),
    path('', include('notification_system.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post_system/urls.py
from django.urls import path
from django.urls import reverse_lazy
from .views import *

urlpatterns = [
    path('create-post/', CreatePostView.as_view(), name='create-post'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('get_model_data/<int:pk>/', get_model_data, name='post-data'),
    path('like-post/', like_post, name='like-post'),
    path('comment-post', comment_post, name='comment-post'),
    path('hashtags-posts/<str:pk>/', HashtagPosts.as_view(), name='hashtag-posts'),

]

app_name = 'post_system'

post_system/models.py
from django.db import models
from user.models import CustomUser


class Post(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='posts')
    hashtags = models.ManyToManyField('Hashtag', blank=True)

    content = models.FileField(upload_to='posts/')
    description = models.TextField(max_length=2200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'post'
        verbose_name_plural = 'posts'


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='likes')

    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    content = models.TextField(max_length=1500)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        return self.user


class Hashtag(models.Model):
    title = models.CharField(max_length=255, unique=True)
    post_count = models.IntegerField(default=0)

    def count_posts(self):
        self.post_count = Post.objects.filter(content__icontains=self.title).count()
        self.save()

    def __str__(self):
        return self.title

post_system/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['description', 'content']
        widgets = {
            "description": forms.TextInput(attrs={"class": "form-control"}),
            "content": forms.FileInput(attrs={"class": "form-control"}),
        }

post_system/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DetailView, View, TemplateView, DeleteView
from .models import *
from .forms import PostCreateForm
from .mixins import RedirectToPreviousMixin
from django.http import JsonResponse
from django.core.serializers import serialize
from notification_system.models import Notification


class CreatePostView(RedirectToPreviousMixin ,CreateView):
    def post(self, request, *args, **kwargs):
        form = PostCreateForm(data=request.POST, files=request.FILES)
        hashtag_list = []
        if request.POST.get('hashtags'):
            for hashtag in request.POST.get('hashtags').split():
                hashtagg = Hashtag.objects.get_or_create(title=hashtag)
                hashtag_list.append(hashtagg[0])
        else:
            hashtag_list = None

        if form.is_valid():
            post = Post.objects.create(
                user=request.user,
                content=form.cleaned_data.get('content'),
                description=form.cleaned_data.get('description'),
            )
            post.save()
            if hashtag_list:
                for i in hashtag_list:
                    post.hashtags.add(i)
            return redirect('user:profile', pk = request.user.id)
        else:
            return HttpResponse('Invalid form')


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_system/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post=self.get_object())
        context['likes'] = Like.objects.filter(post=self.get_object()).count()
        context['is_liked'] = Like.objects.filter(post=self.get_object(), user=self.request.user).exists()
        return context


def get_model_data(request, pk):
    try:
        instance = Post.objects.get(pk=pk)
        queryset = Comment.objects.filter(post=instance)
        comments = []
        hashtags = []
        for comment in queryset:
            comments.append({
                'id': comment.id,
                'post': comment.post_id,
                'username': comment.user.username,
                'user_avatar': comment.user.avatar.url,
                'content': comment.content,
                'created_at': comment.created_at,
            })
        if instance.hashtags.all():
            for hashtag in instance.hashtags.all():
                hashtags.append({
                    'id': hashtag.id,
                    'title': hashtag.title
                })
        data = {
            'id': instance.id,
            'user': instance.user.username,
            'user_id': instance.user.id,
            'user_avatar': instance.user.avatar.url,
            'content': instance.content.url,
            'description': instance.description,
            'created_at': instance.created_at,
            'likes_count': Like.objects.filter(post=instance).count(),
            'is_liked': Like.objects.filter(post=instance, user=request.user).exists(),

        }
        data['hashtags'] = hashtags
        data['comments'] = comments
        return JsonResponse(data)
    except Post.DoesNotExist:
        return JsonResponse({'error': 'Model not found'}, status=404)


def like_post(request):
    if request.method == 'POST':
        id = request.POST.get('postId')
        user_id = request.POST.get('userId')
        post = Post.objects.get(id=id)
        if Like.objects.filter(post=post, user=request.user).exists():
            Like.objects.filter(post=post, user=request.user).delete()
        else:
            Like.objects.create(post=post, user=request.user)
            if request.user.id != post.user.id:
                Notification.objects.create(user = CustomUser.objects.get(id = user_id),
                                    message= f'{request.user.username} liked post {post.id}',
                                    html = (
                f'        <img src="{request.user.avatar.url}" alt="Profile Picture" class="profile-picture">'
                f'        <div class="notification-message">'
                f'            <a href="/profile/{request.user.id}/">{request.user.username}</a> вподобав ваш пост'
                f'            <a><img class="post-action-img" src="{post.content.url}"></a>'
                f'        </div>'
                ))
        
        data = {
            'likes_count': Like.objects.filter(post=post).count(),
            'is_liked': Like.objects.filter(post=post, user=request.user).exists()
        }
        referer = request.META.get('HTTP_REFERER', '/')
        return redirect(referer)
    
    return JsonResponse({'error': 'Invalid request'}) 

def comment_post(request):
    if request.method == 'POST':
        request_user = request.user
        post_id = request.POST.get('postIdCom')
        content = request.POST.get('com-content')
        user_id = request.POST.get('userIdCom')
        post = Post.objects.get(id=post_id)
        Comment.objects.create(post=post, user=request_user, content=content)
        if request_user.id != post.user.id:
            Notification.objects.create(user = CustomUser.objects.get(id = user_id),
                                                message= f'{request_user.username} commented post {post_id}',
                                                html = (
            f'        <img src="{request_user.avatar.url}" alt="Profile Picture" class="profile-picture">'
            f'        <div class="notification-message">'
            f'            <a href="/profile/{request_user.id}/">{request_user.username}</a> коментував ваш пост: {content}'
            f'            <a><img class="post-action-img" src="{post.content.url}"></a>'
            f'        </div>'
            ))
        referer = request.META.get('HTTP_REFERER', '/')
        return redirect(referer)


class HashtagPosts(ListView):
    model = Post
    template_name = 'post_system/hashtag_posts.html'
    context_object_name = 'posts'

    def get(self, request, *args, **kwargs):
        hashtag = Hashtag.objects.get(title=kwargs['pk'])
        posts = Post.objects.filter(hashtags=hashtag)
        context = {
            'posts': posts,
            'hashtag':hashtag,
        }
        return render(request, self.template_name, context)

templates/post_system/create_post.html
{% load static %}
<link rel="stylesheet" href="{% static '/css/post_create.css' %}">

<div id="modalCreatePost" class="modalCreatePost">
    <div class="modal-content">
        <span class="close-btn">&times;</span>
        <h1>Створити пост</h1>
        <form enctype="multipart/form-data" method="post" action="{% url 'post_system:create-post' %}">
            <div class="container-create-post">
                {% csrf_token %}
                <div class="left-panel">
                    <div class="image-upload-section">
                        <label for="image-upload" class="image-upload-btn">
                            <span>+</span>
                            <input type="file" id="image-upload" name="content" style="display: none;" onchange="previewImage(event)">
                        </label>
                        <img id="image-preview" src="" alt="Image Preview" style="display: none;">
                    </div>
                </div>
                <div class="right-panel">
                    <div class="description-section">
                        <textarea class="description" name="description" placeholder="Опис"></textarea>
                    </div>
                    <div class="hashtags-section">
                        <input class="hashtags" name="hashtags" placeholder="Хештеги - писати через пробіл"></input>
                    </div>
                    <div class="submit-section">
                        <button type="submit" class="submit-btn">Опублікувати</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="{% static 'js/imgPreview.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

templates/post_system/hashtag_posts.html
{% extends 'cocon/home.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/css/hashtag_posts.css' %}">
<link rel="stylesheet" href="{% static '/css/interestings.css' %}">


<h1 class="main-hashtag">#{{hashtag.title}}</h1>
<div class="interestings-container">
    <div class="gallery">
        {% for post in posts%}
            <div class="gallery-item" onclick="imgDetail('{{post.id}}')"><img src="{{post.content.url}}" alt=""></div>
        {% endfor %}
    </div>
</div>

<script src="{% static 'js/imgDetail.js' %}"></script>
{% endblock %}

templates/post_system/post_detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/post_detail.css' %}">
<script  src = "https://code.jquery.com/jquery -3.6.4.min.js" > </script> 

<div id="postModal" class="post-modal">
    <div class="modal-post-content">
        <span class="close">&times;</span>
        <div class="modal-post-body">
            <div class="modal-img-post-div">
                <img id="modalImage" src="" alt="Modal Image">
            </div>
            <div class="post-info">
                <div class="userbox">
                    <img src="" alt="User Avatar" id="modalUserAvatar">
                    <div class="user-details">
                        <p class="modalUsername"></p>
                        <p class="post-timestamp" id="postCreatedAt"></p>
                    </div>
                </div>
                <div class="hashtag-container" id="postHashtags"></div>
                <div class="comment-section">
                    <div class="comment-list" id="comment-list"></div>
                </div>
                <div class="post-controls">
                    <form class="like-form" action="{% url 'post_system:like-post' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" id="postId" name="postId" value=""/>
                        <input type="hidden" id="userId" name="userId" value=""/>
                        <button class="like-button" id="likeButton">
                            <i class="like-icon"></i> Like
                        </button>
                    </form>
                    <form class="comment-form" action="{% url 'post_system:comment-post' %}" method="post" id="comment-form">
                        {% csrf_token %}
                        <input type="text" placeholder="Add a comment..." name="com-content" class="comment-input">
                        <input type="hidden" id="postIdCom" name="postIdCom" value=""/>
                        <input type="hidden" id="userIdCom" name="userIdCom" value=""/>
                        <button type="submit" class="submit-comment">Надіслати</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>