chat_system/urls.py
from django.urls import path
from django.urls import reverse_lazy
from .views import *

urlpatterns = [
    path('chatlist/', chat_list, name='chat_list'),
    path('create-chat/<int:pk>/', createchat, name='create-chat'),
    path('chat/<int:pk>/', chat_detail, name='chat-detail'),
    path('chat/', chat_base, name='chat'),
    path('chat/<int:pk>/send-message/', SendMessageView.as_view(), name='send-message'),
]

app_name = 'chat_system'

cocon/urls.py
from django.urls import path
from django.urls import reverse_lazy
from .views import *

urlpatterns = [
    path('', NewsFeedView.as_view(), name='newsfeed'),
    path('leftmenu/', LeftMenuView.as_view(), name='leftmenu'),
    path('search/', search_view, name='search'),
    path('search/results/<str:choose_output>/', search_results, name='search_results'),
    path('interestings/', InterestingsView.as_view(), name='interestings'),
]

app_name = 'cocon'

core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('cocon.urls')),
    path('', include('post_system.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('chat_system.urls')),
    path('', include('notification_system.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification_system/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

urlpatterns = [
    path('notifications/', NotificationList.as_view(), name='notifications'),
    path('notifications/following-request/<int:pk>/action', ActionFollowRequest.as_view(), name='action-follow-request'),

]

app_name = 'notification_system'

post_system/urls.py
from django.urls import path
from django.urls import reverse_lazy
from .views import *

urlpatterns = [
    path('create-post/', CreatePostView.as_view(), name='create-post'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('get_model_data/<int:pk>/', get_model_data, name='post-data'),
    path('like-post/', like_post, name='like-post'),
    path('comment-post', comment_post, name='comment-post'),
    path('hashtags-posts/<str:pk>/', HashtagPosts.as_view(), name='hashtag-posts'),

]

app_name = 'post_system'

user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

urlpatterns = [
    path('login/', LoginView.as_view(template_name='user/login.html' , extra_context={'next': reverse_lazy('cocon:home')}), name='login'),
    path('register/', RegisterView.as_view(template_name='user/register.html'), name='register'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('user:login')), name='logout'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('update-user-info/<int:pk>/', UpdateUserInfo.as_view(), name='update-user-info'),
    path('follow/<int:pk>/', FollowUser.as_view(), name='follow'),
]

app_name = 'user'

cocon/models.py
from django.db import models

# Create your models here.

cocon/views.py
from typing import Any
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from user.models import CustomUser
from notification_system.models import Notification
from user.models import FollowRequest
from post_system.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from chat_system.models import Chat, Message


class LeftMenuView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            unread_messages = 0
            notifications = Notification.objects.filter(user=request.user, is_seen=False)
            followrequests = FollowRequest.objects.filter(to_user=request.user)
            for notification in notifications:
                unread_messages += 1
            for followrequest in followrequests:
                unread_messages += 1
            
            unread_chat = 0
            chats = Chat.objects.filter(members__id=request.user.id)
            for chat in chats:
                unread_chat += chat.messages.filter(is_seen=False).exclude(sender=request.user).count()
            
            context = {
                'unread_messages': unread_messages,
                'unread_chat': unread_chat,
            }
        return render(request, 'cocon/left_menu.html', context=context)


def search_view(request):
    return render(request, 'cocon/search/search.html')

def search_results(request, choose_output):
    query = request.GET.get('search', '')

    if choose_output == 'users':
        all_users = CustomUser.objects.all()
        if query:
            users = all_users.filter(username__icontains=query)
        else:
            users = []

        context = {
            'users': users[:5],
            'choose_output': choose_output,
        }

        return render(request, 'cocon/search/search_results.html', context)

    elif choose_output == 'hashtags':
        all_hashtags = Hashtag.objects.all()
        if query:
            hashtags = all_hashtags.filter(title__icontains=query)
        else:
            hashtags = []

        context = {
            'hashtags': hashtags[:5],
            'choose_output': choose_output,
        }

        return render(request, 'cocon/search/search_results.html', context)


class InterestingsView(ListView):

    model = Post
    template_name = 'cocon/interestings.html'
    context_object_name = 'posts'
    ordering = ['-created_at']

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__profile_is_private=False)


class NewsFeedView(ListView):
    model = Post
    template_name = 'cocon/news_feed.html'
    context_object_name = 'posts'
    ordering = ['-created_at']
    paginate_by = 3

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            super().get(request)
        
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return render(request, 'cocon/post.html', context=self.get_context_data())
            
            return render(request, self.template_name, self.get_context_data())
        else:
            return redirect('user:login')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__in=self.request.user.following.all())
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        if self.request.user:
            context['following'] = self.request.user.following.all()
        return context

templates/cocon/home.html
{% extends 'base.html' %}

{% block body %}
<header class="header">
    <div class="container">
        <div class="logo">
            <a href="{% url 'cocon:newsfeed' %}">
                Cogito Connect
            </a>
        </div>
        <div class="user-info">
            {% if user.is_authenticated %}
                <div class="user-name">
                    <a href="{% url 'user:profile' request.user.id%}">{{ request.user.username }}</a>
                </div>
            {% else %}
                <div class="user-actions">
                    <a href="{% url 'user:login' %}">Login</a>
                    <a href="{% url 'user:register' %}">Register</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>

{% block leftmenu %}
{% include 'cocon/left_menu.html' %}
{% endblock %}

<!-- Content Section -->
<div class="content">
    {% include 'post_system/create_post.html' %}
    {% include 'post_system/post_detail.html' %}
    {% block content %}

    {% endblock %}
</div>


{% endblock %}

templates/cocon/interestings.html
{% extends 'cocon/home.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/css/interestings.css' %}">

<div class="interestings-container">
    <div class="gallery">
        {% for post in posts%}
            <div class="gallery-item" onclick="imgDetail('{{post.id}}')"><img src="{{post.content.url}}" alt=""></div>
        {% endfor %}
    </div>
</div>

<script src="{% static 'js/imgDetail.js' %}"></script>
{% endblock %}

templates/cocon/left_menu.html
{% load static %}
<div class="left-menu" id="left-menu">
    <nav class="menu">
        <ul>
            <li><a href="{% url 'cocon:newsfeed' %}"><i class="fa-solid fa-house"></i> Головна</a></li>
            <li><a href="{% url 'cocon:search' %}"><i class="fa-solid fa-magnifying-glass"></i> Пошук</a></li>
            <li><a href="{% url 'cocon:interestings' %}"><i class="fa-solid fa-mug-hot"></i> Цікаве</a></li>
            <li><a href="{% url 'chat_system:chat' %}"><i class="fa-regular fa-comment"></i> Повідомлення 
                {% if unread_chat %}
                <div class="unread-circle">
                    <span class="unread-number">{{unread_chat}}</span>
                </div>
                {% endif %}
            </a></li>
            <li><a href="{% url 'notification_system:notifications' %}"><i class="fa-solid fa-inbox"></i> Сповіщення  
                {% if unread_messages %}
                <div class="unread-circle notif-circle">
                    <span class="unread-number">{{unread_messages}}</span>
                </div>
                {% endif %}
            </a></li>
            <li><a href="#" id="openPostCreate"><i class="fa-solid fa-plus"></i> Створити</a></li>
            <li>
                <a href="{% url 'user:profile' request.user.id%}">
                    <img src="{{request.user.avatar.url}}" alt="" style="width: 30px; height: 30px; border-radius: 50%;">
                    <span>Профіль</span>
                </a>
            </li>
            <li style="margin-top: 270px;" onclick="dropdownMore()" class="dropbtn"><a href="#"><i class="fa-solid fa-bars"></i> Більше</a></li>
        </ul>
        <div id="myDropdown" class="dropdown-content">
            <a href="{% url 'user:update-user-info' request.user.id %}">Налаштування</a>
            <form method="post" action="{% url 'user:logout' %}">
                {% csrf_token %}
                <button type="submit" class="logout-menu-btn">Вийти</button>
            </form>
        </div>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

templates/cocon/news_feed.html
{% extends 'cocon/home.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/css/newsfeed.css' %}">

<div class="feed-container">
    {% include 'cocon/post.html' %}
</div>
{% if not following %}
    <h1 class="empty-text">Тут поки пусто. Підпишіться на когось щоб бачити нові пости</h1>
{% else %}
<div class="morediv">
    <button class="show-more-posts" id="show-more-posts" onclick="showMorePosts()">Показати ще</button>
</div>
{% endif %}
<input type="hidden" id="page-cur" value="{{page_obj.number}}">
<input type="hidden" id="page-num" value="{{page_obj.paginator.num_pages}}">

<script src="{% static 'js/showMorePosts.js' %}"></script>
<script src="{% static 'js/imgDetail.js' %}"></script>
{% endblock %}

templates/cocon/post.html
{% load static %}
{% load cocon_custom_tags %}
{% for post in page_obj %}
        <div class="post-card">
            <div class="post-header">
                <img class="profile-img" src="{{post.user.avatar.url}}" alt="Profile Image">
                <div class="user-info">
                    <a href="{% url 'user:profile' post.user.id %}"><p class="username">{{post.user.username}}</p></a>
                    <p class="timestamp">{{post.created_at|date:"F j, Y, g:i a"}}</p>
                </div>
            </div>
            <div class="post-content">
                <p>{{post.description}}</p>
                <img src="{{post.content.url}}" alt="Post Image">
                {%for hashtag in post.hashtags.all%}<a href="{% url 'post_system:hashtag-posts' hashtag.title%}">#{{hashtag}} </a>{%endfor%}
            </div>
            <div class="post-footer">
                <div class="footer-icon">
                    <form action="{% url 'post_system:like-post' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" id="postId" name="postId" value="{{post.id}}"/>
                        <input type="hidden" id="userId" name="userId" value="{{post.user.id}}"/>
                        <button class="likeBut" id="likeButton">{% if post|is_liked:request.user %}<i class="fa-solid fa-heart"></i>{%else%}<i class="far fa-heart">{%endif%}</i>{{post|likes_count}}</button>
                    </form>
                </div>
                <div class="footer-icon">
                    <p onclick="imgDetail('{{post.id}}')"><i class="far fa-comment"></i> Comment</p>
                </div>
            </div>
        </div>
    {% endfor %}