chat_system/urls.py
from django.urls import path
from django.urls import reverse_lazy
from .views import *

urlpatterns = [
    path('chatlist/', chat_list, name='chat_list'),
    path('create-chat/<int:pk>/', createchat, name='create-chat'),
    path('chat/<int:pk>/', chat_detail, name='chat-detail'),
    path('chat/', chat_base, name='chat'),
    path('chat/<int:pk>/send-message/', SendMessageView.as_view(), name='send-message'),
]

app_name = 'chat_system'

core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('cocon.urls')),
    path('', include('post_system.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('chat_system.urls')),
    path('', include('notification_system.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

urlpatterns = [
    path('login/', LoginView.as_view(template_name='user/login.html' , extra_context={'next': reverse_lazy('cocon:home')}), name='login'),
    path('register/', RegisterView.as_view(template_name='user/register.html'), name='register'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('user:login')), name='logout'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('update-user-info/<int:pk>/', UpdateUserInfo.as_view(), name='update-user-info'),
    path('follow/<int:pk>/', FollowUser.as_view(), name='follow'),
]

app_name = 'user'

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars', blank=True, default='/default_avatar.png')
    bio = models.TextField(blank=True)
    followers = models.ManyToManyField('self', related_name='user_followers', symmetrical=False, blank=True)
    following = models.ManyToManyField('self', related_name='user_following', symmetrical=False, blank=True)
    profile_is_private = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class FollowRequest(models.Model):
    from_user = models.ForeignKey(CustomUser, related_name='from_user', on_delete=models.CASCADE)
    to_user = models.ForeignKey(CustomUser, related_name='to_user', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.from_user} хоче слідкувати за {self.to_user}"

user/forms.py
from typing import Any
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django import forms


class RegisterForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username", "avatar", "bio", "password1", "password2"]
        widgets = {
            "avatar": forms.FileInput()
        }


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["username", "avatar", "bio", "profile_is_private"]
        widgets = {
            "avatar": forms.FileInput(),
            "profile_is_private": forms.CheckboxInput()
        }
    

user/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, View
from .models import *
from post_system.models import Post
from django.contrib.auth.decorators import login_required
from .mixins import *
from django.utils.decorators import method_decorator
from notification_system.models import Notification
from django.utils import timezone



class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = "user/register.html"
    success_url = reverse_lazy("cocon:home")
    def form_valid(self, form):
        user = form.save()
    
        if user:
            login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
            if user.is_authenticated:
                return HttpResponseRedirect(self.success_url)
            else:
                return redirect("user:login")

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class UserProfileView(View, UserIsOwnerMixin):
    template_name = "user/user_profile.html"

    def get(self, request, *args, **kwargs):
        user = CustomUser.objects.get(id=kwargs['pk'])
        user_follower_count = user.followers.count()
        user_following_count = user.following.count()
        user_posts_count = Post.objects.filter(user=user).count()
        user_posts = Post.objects.filter(user=user)

        user_profile_is_private = user.profile_is_private
        user_is_followed = user.followers.filter(id=request.user.id).exists() or user.id == request.user.id
        follow_request_exists = FollowRequest.objects.filter(from_user=request.user, to_user=user)

        context = {
            'user':user,
            'following': user_following_count,
            'followers': user_follower_count,
            'user_posts_count': user_posts_count,
            'user_posts': user_posts,
            'user_profile_is_private': user_profile_is_private,
            'user_is_followed': user_is_followed,
            'follow_request': follow_request_exists,
        }

        return render(request, self.template_name, context=context)


@method_decorator(login_required, name='dispatch')
class UpdateUserInfo(View, UserIsOwnerMixin):
    def post(self, request, *args, **kwargs):
        form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        
        if CustomUser.objects.filter(username=request.POST.get('username')).exclude(id=request.user.id).exists():
            messages.error(request, "Username already exists")
            return render(request, "user/change_user_info.html", {'form':form})
        else:
            if form.is_valid():
                form.save()
                return redirect('user:profile', pk=request.user.id)
    
    def get(self, request, *args, **kwargs):
        form = UserUpdateForm(instance=request.user)
        return render(request, "user/change_user_info.html", {'form':form})


class FollowUser(View):
    def post(self, request, *args, **kwargs):
        user = CustomUser.objects.get(id=kwargs['pk'])
        request_user = request.user
        user_is_followed = user.followers.filter(id=request.user.id).exists()
        if user_is_followed:
            user.followers.remove(request.user)
            request_user.following.remove(user)
        elif not user_is_followed:
            if user.profile_is_private:
                FollowRequest.objects.create(from_user=request.user, to_user=user)
            else:
                Notification.objects.create(user = user,
                                            message= f'{request_user.username} followed {user.username} ',
                                            html = (
        f'        <img src="{request_user.avatar.url}" alt="Profile Picture" class="profile-picture">'
        f'        <div class="notification-message">'
        f'            <a href="/profile/{request_user.id}/">{request_user.username}</a> підписався(-лась) на вас'
        f'        </div>'
    )
)
                user.followers.add(request.user)
                request_user.following.add(user)
        return redirect('user:profile', pk=user.id)

templates/user/change_user_info.html
{% extends 'cocon/home.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/change_user_info.css' %}">

<a href="{% url 'user:profile' user.id %}"><i class="fa-solid fa-arrow-left fa-xl back-btn" style="color: #ffffff;"></i></a>
<div class="change-container">
    <div class="profile-section">
        <img src="{{user.avatar.url}}" alt="Profile Picture" class="profile-pic" id="pic">
        <h2 class="username">{{user.username}}</h2>
    </div>
    <form class="update-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="avatar">Аватар</label>
            <input type="file" id="avatar" name="avatar" accept="image/*">
        </div>
        <div class="form-group">
            <label for="username">Ім'я</label>
            <input type="text" id="username" name="username" value="{{ form.username.value|default:'' }}">
            {% if form.username.errors %}
            <div class="error">
                {% for error in form.username.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="bio">Біо</label>
            <textarea id="bio" name="bio">{{ form.bio.value|default:'' }}</textarea>
        </div>
        <div class="form-group">
            <label for="profile_is_private" >Приватний профіль</label>
            <input type="checkbox" id="switch" class="custom-switch" name="profile_is_private" {% if form.profile_is_private.value %}checked{% endif %}>
            <label for="switch" class="switch-label custom-switch-label"></label>
        </div>
        <button type="submit" class="btn-update">Update Profile</button>
    </form>
</div>

<script src="{% static 'js/imgEvent.js' %}"></script>
{% endblock %}

templates/user/login.html
{% extends 'auth_base.html' %}

{% block content %}
{% load socialaccount %}
{% block title %}<title>Login</title>{% endblock %}

<h1 style="font-size: 32px;">Cogito Connect</h1>
<div class="login-container">
    <h2>Login</h2>
    <form action="{% url 'user:login' %}" method="post" class="form">
        {% csrf_token %}
        <div class="input-group">
            <label for="username">Username</label>
            <input type="text" id="username" name="username" required>
            {% for error in form.username.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="input-group">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" required>
            {% for error in form.password.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <button type="submit" class="login-button">Login</button>
    </form>
    <div class="separator">
        <span>or</span>
    </div>
    <a href="{% provider_login_url 'google' %}" class="google-button">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="24px" height="24px">
            <path fill="#4285F4" d="M24 9.5c3.1 0 5.2 1.3 6.4 2.4L34 9c-2.6-2.5-6.1-4-10-4C16.1 5 10.1 9 8.1 14.4l5.9 4.6c1.4-4.2 5.2-7.5 10-7.5z"/>
            <path fill="#34A853" d="M13.3 22.3c-.3-1-.5-2-.5-3s.2-2 .5-3L7.4 12c-1.1 2.2-1.7 4.6-1.7 7 0 2.5.6 4.8 1.7 7l5.9-4.7z"/>
            <path fill="#FBBC05" d="M24 37c-3.9 0-7.4-1.5-10-4l-5.9 4.7C10.1 39 16.1 43 24 43c3.9 0 7.4-1.3 10-3.6l-5.9-4.7c-1.2 1.1-3.3 2.3-6.4 2.3z"/>
            <path fill="#EA4335" d="M34 24c0-.8-.1-1.5-.2-2.2H24v4.5h5.9c-.3 1.4-1.1 2.5-2.1 3.3l5.9 4.7c2.5-2.2 4-5.4 4-9.3z"/>
            <path fill="none" d="M0 0h48v48H0z"/>
        </svg>
        Sign in with Google
    </a>
    <div class="signup-container">
        <span>Don't have an account?</span>
        <a href="{% url 'user:register' %}" class="signup-button">Sign Up</a>
    </div>
</div>
{% endblock %}

templates/user/register.html
{% extends 'auth_base.html' %}

{% block content %}
{% load socialaccount %}
{% block title %}<title>Sign Up</title>{% endblock %}

<h1 style="font-size: 32px;">Cogito Connect</h1>
<div class="login-container">
    <h2>Sign Up</h2>
    <form id="signup-form" action="{% url 'user:register' %}" method="post" class="form" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="input-group">
            <label for="signup-username">Username</label>
            <input type="text" id="signup-username" name="username" required>
            {% for error in form.username.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="input-group">
            <label for="password1">Password</label>
            <input type="password1" id="password1" name="password1" required>
            {% for error in form.password1.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="input-group">
            <label for="password2">Confirm Password</label>
            <input type="password2" id="password2" name="password2" required>
            {% for error in form.password2.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="input-group">
            <label for="bio">Bio</label>
            <textarea id="bio" name="bio" rows="3" required></textarea>
        </div>
        <div class="input-group">
            <label for="avatar">Avatar</label>
            <input type="file" id="avatar" name="avatar" accept="image/*" required>
        </div>
        <button type="submit" class="login-button">Sign Up</button>
    </form>
    <div class="separator">
        <span>or</span>
    </div>
    <a href="{% provider_login_url 'google' %}" class="google-button">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="24px" height="24px">
            <path fill="#4285F4" d="M24 9.5c3.1 0 5.2 1.3 6.4 2.4L34 9c-2.6-2.5-6.1-4-10-4C16.1 5 10.1 9 8.1 14.4l5.9 4.6c1.4-4.2 5.2-7.5 10-7.5z"/>
            <path fill="#34A853" d="M13.3 22.3c-.3-1-.5-2-.5-3s.2-2 .5-3L7.4 12c-1.1 2.2-1.7 4.6-1.7 7 0 2.5.6 4.8 1.7 7l5.9-4.7z"/>
            <path fill="#FBBC05" d="M24 37c-3.9 0-7.4-1.5-10-4l-5.9 4.7C10.1 39 16.1 43 24 43c3.9 0 7.4-1.3 10-3.6l-5.9-4.7c-1.2 1.1-3.3 2.3-6.4 2.3z"/>
            <path fill="#EA4335" d="M34 24c0-.8-.1-1.5-.2-2.2H24v4.5h5.9c-.3 1.4-1.1 2.5-2.1 3.3l5.9 4.7c2.5-2.2 4-5.4 4-9.3z"/>
            <path fill="none" d="M0 0h48v48H0z"/>
        </svg>
        Sign up with Google
    </a>
    <div class="signup-container">
        <span>Already have an account?</span>
        <a href="{% url 'user:login' %}" class="signup-button">Login</a>
    </div>
</div>
{% endblock %}

templates/user/user_profile.html
{% extends 'cocon/home.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/profile.css' %}">

<div class="profile-container">
    <header class="profile-header">
        <div class="profile-image">
            <img src="{{user.avatar.url}}" alt="Profile Picture">
        </div>
        <div class="profile-details">
            <div class="profile-username">
                <h1>{{user.username}}</h1>
                {% if user == request.user %}
                <a href="{% url 'user:update-user-info' request.user.id %}" class="edit-profile-button">Редагувати профіль</a>
                {% else %}
                <div class="profile-actions">
                    <form action="{% url 'user:follow' user.id%}" method="post">
                    {% csrf_token %}
                    {% if user_is_followed %}
                        <button class="unfollow-button">Відписатись</button>
                    {% else %}
                        {% if user_profile_is_private %}
                            {% if follow_request %}
                                <button class="follow-button" disabled>Очікує підтвердження</button>
                            {% else %}
                                <button class="follow-button">Підписатись</button>
                            {% endif %}
                        {% else %}
                            <button class="follow-button">Підписатись</button>
                        {% endif %}
                    {% endif %}
                    </form>
                    <a class="message-button" href="{% url 'chat_system:create-chat' user.id %}">Повідомлення</a>
                </div>
                {% endif %}
            </div>
            <ul class="profile-stats">
                <li><span class="stat-number">{{user_posts_count}}</span> публікацій</li>
                <li><span class="stat-number">{{followers}}</span> підписників</li>
                <li><span class="stat-number">{{following}}</span> підписок</li>
            </ul>
            <div class="profile-bio">
                <p>{{user.bio}}</p>
            </div>
        </div>
    </header>
    <section class="profile-gallery">
        {% if user_profile_is_private %}
            {% if user_is_followed %}
                {% if user_posts %}
                    {% for post in user_posts %}
                    <div class="gallery-item" onclick="imgDetail('{{post.id}}')"><img src="{{post.content.url}}" alt="Gallery Image 1"></div>
                    {% endfor %}
                {% endif %}
            {% else %}
                <div class="private-profile-sign">
                    <img src="{% static '/img/lock.png' %}" alt="">
                    <h1>Цей профіль приватний</h1>
                </div>
            {% endif %}
        {% else %}
            {% if user_posts %}
                {% for post in user_posts %}
                <div class="gallery-item" onclick="imgDetail('{{post.id}}')"><img src="{{post.content.url}}" alt="Gallery Image 1"></div>
                {% endfor %}
            {% endif %}
        {% endif %}
    </section>
</div>

<script src="{% static 'js/imgDetail.js' %}"></script>
{% endblock %}